apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "s3www.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.s3www.ingressPort }}
      targetPort: {{ .Values.s3www.port }}

  type: ClusterIP
